### PR TITLE
Add option to modify the query

### PR DESCRIPTION
**Pull request by KeizerDev**
I needed an option to add a where clause so I can show data related to the user.

Before:
```php
  protected function getStats(): array
  {
      $simpleStat = SimpleStat::make(MyModel::class);
  
      $simpleStat->trend = Trend::model(MyModel::class)->query(MyModel::where('user_id', auth()->id()));
  
      return [
          $simpleStat->last7Days()->dailyCount()->color('success'),
      ];
  }
```

Now:
```php
  protected function getStats(): array
  {
      return [
          SimpleStat::make(MyModel::class)->where('user_id', auth()->id())->last7Days()->dailyCount()->color('success'),
      ];
  }
```

### CODE REVIEW

**Comment by KeizerDev** [comment]
I just noticed there will be an issue with this code as `$this->trend->query(...)` returns a new instance of `Trend`.

**Comment by KeizerDev** [comment]
Squashed all commits to just one, PR is ready.

**Comment by freekmurze** [comment]
Could you also add a test for this and add an example to the readme?

**Comment by KeizerDev** [comment]
@freekmurze done. If there are any comments please let me know!

**Comment by timvandijck** [comment]
@KeizerDev looks good, thanks for the contribution!

**Pull request merged**
